import type { DesktopApi } from "../src/platform/desktop/contracts";
import { getAppSettingsPath, loadAppSettings, saveAppSettings } from "./appSettings";
import {
  addPullRequestComment,
  connectProvider,
  disconnectProvider,
  getPullRequestBuildStatuses,
  getPullRequestConversation,
  getPullRequestFiles,
  getPullRequestPatch,
  getPullRequestDiffCached,
  likePullRequestComment,
  listProviderConnections,
  listPullRequests,
  mergePullRequest,
  resolveActivePullRequestForBranch,
  preparePullRequestCompareRefs,
  preparePullRequestWorkspace,
  replyToPullRequestThread,
  resolveHostedRepo,
  setPullRequestThreadResolved,
  submitPullRequestReviewComments,
  submitPullRequestReviewDecision,
} from "./hostedRepos";
import { getInboxPullRequests, refreshInboxPullRequests } from "./inbox/orchestrator";
import {
  commitStaged,
  discardAll,
  discardFile,
  discardFiles,
  getBranchFileVersions,
  getBranchFiles,
  getBranches,
  getCommitFileVersions,
  getCommitFiles,
  getCommitHistory,
  getFileVersions,
  getRepoFiles,
  getRepoFile,
  getGitSnapshot,
  stageAll,
  stageFile,
  unstageAll,
  unstageFile,
} from "./git";
import { checkAppExists, confirm, openPath, selectFolder } from "./system";
import { loadWorkspaceSession, saveWorkspaceSession } from "./workspaceSession";

export const desktopApi: DesktopApi = {
  selectFolder,
  loadWorkspaceSession,
  saveWorkspaceSession,
  loadAppSettings,
  saveAppSettings,
  getAppSettingsPath,
  confirm,
  checkAppExists,
  openPath,
  listProviderConnections,
  connectProvider,
  disconnectProvider,
  resolveHostedRepo,
  listPullRequests,
  getInboxPullRequests: (input) => getInboxPullRequests(input.repoPath),
  refreshInboxPullRequests: (input) => refreshInboxPullRequests(input.repoPath),
  resolveActivePullRequestForBranch,
  getPullRequestConversation,
  getPullRequestBuildStatuses,
  getPullRequestFiles,
  getPullRequestPatch,
  getPullRequestDiffCached,
  addPullRequestComment,
  replyToPullRequestThread,
  submitPullRequestReviewComments,
  submitPullRequestReviewDecision,
  setPullRequestThreadResolved,
  likePullRequestComment,
  mergePullRequest,
  preparePullRequestCompareRefs,
  preparePullRequestWorkspace,
  getGitSnapshot,
  getRepoFiles,
  getCommitHistory,
  getBranches,
  getBranchFiles,
  getCommitFiles,
  getCommitFileVersions,
  getFileVersions,
  getBranchFileVersions,
  stageFile,
  unstageFile,
  stageAll,
  unstageAll,
  discardFile,
  discardFiles,
  discardAll,
  commitStaged,
  getRepoFile,
};

export function configureDesktopApi() {}

export async function disposeDesktopApi() {}
